api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "cart-price-override"
type = "function"
uid = "324ac35d-22cd-2ab3-62ad-c6293ff65f6f693fcad8"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
